app:
  baseUrl: ${BASE_URL}

backend:
  baseUrl: ${BASE_URL}
  listen: ':7007'

  # config options: https://node-postgres.com/apis/client
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      # ssl:
      #   ca: # if you have a CA file and want to verify it you can uncomment this section
      #     $file: <file-path>/ca/server.crt

auth:
  environment: production
  providers:
    google:
      production:
        clientId: ${AUTH_GOOGLE_CLIENT_ID}
        clientSecret: ${AUTH_GOOGLE_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityAnnotation

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Template, User, Group]
  locations:
    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]
    - type: file
      target: ./catalog/systems.yaml
    - type: url
      target: https://github.com/rikukaInoue/rellf-auth/blob/main/catalog-info.yaml
    - type: url
      target: https://github.com/rikukaInoue/rellf-authz/blob/main/catalog-info.yaml
    - type: file
      target: ./catalog/rikukadev.yaml
    - type: file
      target: ./catalog/react-router-lambda-demo.yaml
    - type: file
      target: ./catalog/rel-ui.yaml
    - type: file
      target: ./catalog/harmony-etml.yaml
    - type: file
      target: ./catalog/my-backstage.yaml
