---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: taishi.inoue
  annotations:
    google.com/email: t.i.systems28@gmail.com
spec:
  memberOf: [admins]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admins
spec:
  type: team
  children: []
