---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: example.user
  annotations:
    google.com/email: user@example.com
spec:
  memberOf: [admins]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admins
spec:
  type: team
  children: []
